server:
  port: 8085
spring:
  main:
    web-application-type: reactive
  application:
    name: online-judge-gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: online-judge-question-service
          uri: lb://online-judge-question-service
          predicates:
            - Path=/api/question/**
        - id: online-judge-judge-service
          uri: lb://online-judge-judge-service
          predicates:
            - Path=/api/judge/**
        - id: online-judge-user-service
          uri: lb://online-judge-user-service
          predicates:
            - Path=/api/user/**
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.cloud.loadbalancer: trace
    org.springframework.web.reactive: trace
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2